function y = mylowpassfilter(x)

%MYLOWPASSFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the DSP System Toolbox 8.5.
% Generated on: 06-May-2014 22:18:04

persistent Hd;

if isempty(Hd)
    
    Fpass = 0.055;  % Passband Frequency
    Fstop = 0.9;    % Stopband Frequency
    Apass = 1;      % Passband Ripple (dB)
    Astop = 30;     % Stopband Attenuation (dB)
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    set(Hd,'PersistentMemory',false);
    
end

y = filter(Hd,x);


